BEBOPs:
  camera_1:
    model: "pinhole"
    resolution:
      width: 1280
      height: 720
    intrinsic_parameters:
      fx: 1000.0
      fy: 1000.0
      cx: 640.0
      cy: 360.0
      k1: 0.0
      k2: 0.0
      p1: 0.0
      p2: 0.0
      k3: 0.0
    extrinsic_parameters:
      rotation_matrix:
        - [1.0, 0.0, 0.0]
        - [0.0, 1.0, 0.0]
        - [0.0, 0.0, 1.0]
      translation_vector:
        - 0.0
        - 0.0
        - 0.0
  
  B6: # B6_2
    model: "pinhole"
    resolution:
      width: 856
      height: 480
    intrinsic_parameters:
      fx: 540.79
      fy: 532.62
      cx: 430.75
      cy: 241.24
      rd: 0.0
    distortion_coefficients:
      c1: -6.40528596e-03
      c2:  7.32071950e-02
      c3: -4.52528475e-05
      c4:  1.74188724e-03
      c5: -8.43160051e-02
  
  # Add similar blocks for camera_3 to camera_8

