BEBOPs:
  camera_1:
    model: "pinhole"
    resolution:
      width: 1280
      height: 720
    intrinsic_parameters:
      fx: 1000.0
      fy: 1000.0
      cx: 640.0
      cy: 360.0
      k1: 0.0
      k2: 0.0
      p1: 0.0
      p2: 0.0
      k3: 0.0
    extrinsic_parameters:
      rotation_matrix:
        - [1.0, 0.0, 0.0]
        - [0.0, 1.0, 0.0]
        - [0.0, 0.0, 1.0]
      translation_vector:
        - 0.0
        - 0.0
        - 0.0
  
  B6:
    model: "pinhole"
    resolution:
      width: 856
      height: 480
    intrinsic_parameters:
      fx: 595.4
      fy: 583.1
      cx: 425.4
      cy: 268.6
      rd: 0.0
  
  # Add similar blocks for camera_3 to camera_8

