cameras:
  camera_1:
    model: "pinhole"
    resolution:
      width: 1280
      height: 720
    intrinsic_parameters:
      fx: 1000.0
      fy: 1000.0
      cx: 640.0
      cy: 360.0
      k1: 0.0
      k2: 0.0
      p1: 0.0
      p2: 0.0
      k3: 0.0
    extrinsic_parameters:
      rotation_matrix:
        - [1.0, 0.0, 0.0]
        - [0.0, 1.0, 0.0]
        - [0.0, 0.0, 1.0]
      translation_vector:
        - 0.0
        - 0.0
        - 0.0
  
  camera_2:
    model: "pinhole"
    resolution:
      width: 1280
      height: 720
    intrinsic_parameters:
      fx: 950.0
      fy: 950.0
      cx: 640.0
      cy: 360.0
      k1: 0.1
      k2: -0.1
      p1: 0.0
      p2: 0.0
      k3: 0.05
    extrinsic_parameters:
      rotation_matrix:
        - [0.999, 0.01, 0.03]
        - [-0.01, 0.999, -0.02]
        - [-0.03, 0.02, 0.999]
      translation_vector:
        - 0.5
        - 0.0
        - 0.2
  
  # Add similar blocks for camera_3 to camera_8

